x-backend-app-environment: &x-backend-app-environment
  GOMAXPROCS: "1"
  # App
  APP_NAME: "go-clean-template"
  APP_VERSION: "1.0.0"
  # HTTP settings
  HTTP_PORT: "8080"
  HTTP_USE_PREFORK_MODE: "false"
  # Logger
  LOG_LEVEL: "debug"

  # Metrics
  METRICS_ENABLED: "true"
  # Swagger
  SWAGGER_ENABLED: "true"

  #Open weather
  OPEN_WEATHER_API_URL: ${OPEN_WEATHER_API_URL}
  OPEN_WEATHER_API_KEY: ${OPEN_WEATHER_API_KEY}

services:
  app:
    container_name: app
    platform: linux/amd64
    pid: "host"
    build:
      context: .
    environment:
      <<: *x-backend-app-environment
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      app_network:
        aliases:
          - app.lvh.me

  ngrok:
    image: ngrok/ngrok:latest
    command: http bot:8088
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    restart: unless-stopped
    networks:
      app_network:
        aliases:
          - ngrok.lvh.me

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      app_network:
        aliases:
          - nginx.lvh.me

networks:
  app_network:
    external: false