services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app